(() => {
  const root = document.getElementById('pz-ispytaniya-pk-page');
  if (!root) return;
  root.innerHTML = `
  <style>
  #pz-ispytaniya-pk-page .pk-wrap{width:min(1160px,calc(100% - 28px));margin:auto}#pz-ispytaniya-pk-page .pk-hero{padding:76px 0 58px;background:#14364b;color:#fff}#pz-ispytaniya-pk-page .pk-hero-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:30px}#pz-ispytaniya-pk-page .pk-section{padding:56px 0}#pz-ispytaniya-pk-page .pk-pale{background:#f5f7f6}#pz-ispytaniya-pk-page .pk-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}#pz-ispytaniya-pk-page .pk-card{padding:22px;border:1px solid #dfe6e8;border-radius:16px;background:#fff}#pz-ispytaniya-pk-page .pk-form{padding:24px;border-radius:16px;background:#fff;color:#15212b}#pz-ispytaniya-pk-page .pk-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}#pz-ispytaniya-pk-page label{display:flex;flex-direction:column;gap:5px;font-size:13px;color:#465a66}#pz-ispytaniya-pk-page input,#pz-ispytaniya-pk-page select{padding:12px;border:1px solid #cfd9dc;border-radius:7px;font:inherit}#pz-ispytaniya-pk-page .pk-btn{display:inline-block;padding:13px 17px;background:#e54132;color:#fff;border:0;border-radius:8px;font-weight:700;text-decoration:none;cursor:pointer}#pz-ispytaniya-pk-page .pk-alt{background:#fff;color:#14364b}#pz-ispytaniya-pk-page .pk-note{color:#697984}#pz-ispytaniya-pk-page .pk-placeholder{min-height:150px;border:1px dashed #aab8bf;border-radius:10px;padding:18px;color:#697984;background:#f8faf9}#pz-ispytaniya-pk-page table{width:100%;border-collapse:collapse;background:#fff}#pz-ispytaniya-pk-page th,#pz-ispytaniya-pk-page td{padding:12px;border:1px solid #dfe6e8;text-align:left;vertical-align:top}#pz-ispytaniya-pk-page details{padding:13px 0;border-top:1px solid #dfe6e8}#pz-ispytaniya-pk-page summary{font-weight:700;cursor:pointer}@media(max-width:820px){#pz-ispytaniya-pk-page .pk-hero-grid,#pz-ispytaniya-pk-page .pk-grid,#pz-ispytaniya-pk-page .pk-fields{grid-template-columns:1fr}}
  </style>
  <section class="pk-hero"><div class="pk-wrap pk-hero-grid"><div><p>АЛМАТЫ И АЛМАТИНСКАЯ ОБЛАСТЬ</p><h1>Испытание пожарных кранов</h1><p>Проверяем работоспособность внутреннего противопожарного водопровода, фиксируем измерения по точкам и оформляем акт испытаний.</p><p>Методику и применимость измерений подтверждает пожарный инженер с учётом объекта.</p><p><a class="pk-btn" href="#pk-order">Заказать испытания</a> <a class="pk-btn pk-alt" href="#pk-calculator">Рассчитать состав работ</a></p></div><div class="pk-form"><h2>Что зависит от объекта</h2><p class="pk-note">Количество кранов, этажи и зоны, доступ к шкафам, комплектация, необходимость акта, устранения замечаний и повторного испытания.</p><p><a class="pk-btn" href="#pk-calculator">Подобрать состав работ</a></p></div></div></section>
  <section class="pk-section"><div class="pk-wrap"><h2>Когда нужны испытания</h2><div class="pk-grid"><article class="pk-card"><h3>Слабая водоотдача или нестабильное давление</h3><p>Проверяем параметры на согласованных точках и фиксируем измерения.</p></article><article class="pk-card"><h3>Неисправность или неполная комплектация шкафа</h3><p>Осматриваем вентиль, рукав, ствол и указываем замечания по каждой точке.</p></article><article class="pk-card"><h3>Нужен акт испытаний</h3><p>Оформляем акт по согласованному перечню пожарных кранов.</p></article></div></div></section>
  <section class="pk-section pk-pale"><div class="pk-wrap"><h2>Шесть этапов испытаний</h2><div class="pk-grid"><div class="pk-card">1. Сбор исходных данных и перечня кранов</div><div class="pk-card">2. Осмотр шкафов и комплектации</div><div class="pk-card">3. Подготовка точек и безопасной зоны</div><div class="pk-card">4. Испытание и измерение параметров</div><div class="pk-card">5. Фиксация результатов по каждой точке</div><div class="pk-card">6. Оформление акта и перечня замечаний</div></div><p class="pk-note">Устранение дефектов, замена комплектующих и повторное испытание входят только в выбранный пакет или согласуются отдельно.</p></div></section>
  <section class="pk-section"><div class="pk-wrap"><h2>Пакеты испытаний</h2><div class="pk-grid"><article class="pk-card"><h3>Локальный</h3><p><b>Границы:</b> одна зона или ограниченная группа кранов.</p><p><b>Входит:</b> измерения и акт по проверенным точкам.</p><p><b>Не входит:</b> устранение дефектов и повторное испытание.</p><p class="pk-note">Стоимость и срок — после подтверждения числа точек и доступа.</p><a class="pk-btn" href="#pk-order">Выбрать пакет</a></article><article class="pk-card"><h3>Объект</h3><p><b>Границы:</b> согласованный перечень пожарных кранов на объекте.</p><p><b>Входит:</b> испытания, сводный акт и перечень замечаний.</p><p><b>Не входит:</b> ремонт и повторное испытание без отдельного согласования.</p><p class="pk-note">Стоимость и срок — после подтверждения исходных данных.</p><a class="pk-btn" href="#pk-order">Выбрать пакет</a></article><article class="pk-card"><h3>Объект плюс</h3><p><b>Границы:</b> испытания по согласованному объекту.</p><p><b>Входит:</b> дефектовка, согласованное устранение замечаний и повторная проверка.</p><p><b>Не входит:</b> работы и комплектующие вне согласованного перечня.</p><p class="pk-note">Стоимость и срок — после осмотра и согласования работ.</p><a class="pk-btn" href="#pk-order">Выбрать пакет</a></article></div></div></section>
  <section class="pk-section pk-pale"><div class="pk-wrap"><h2>Сравнение пакетов</h2><div style="overflow-x:auto"><table><tr><th>Параметр</th><th>Локальный</th><th>Объект</th><th>Объект плюс</th></tr><tr><td>Объём точек</td><td>Одна зона или ограниченная группа</td><td>Согласованный перечень на объекте</td><td>Согласованный объект с повторной проверкой</td></tr><tr><td>Визуальный осмотр и измерения</td><td>По проверенным точкам</td><td>По согласованному перечню</td><td>По согласованному перечню</td></tr><tr><td>Акт и дефектовка</td><td>Акт по точкам</td><td>Сводный акт и замечания</td><td>Акт, дефектовка и план устранения</td></tr><tr><td>Устранение замечаний</td><td>Не входит</td><td>Отдельно согласуется</td><td>В согласованных границах</td></tr><tr><td>Повторное испытание</td><td>Не входит</td><td>Отдельно согласуется</td><td>После устранения замечаний</td></tr><tr><td>Срок и стоимость</td><td colspan="3">После подтверждения количества точек, этажей/зон, доступа и состояния системы.</td></tr></table></div></div></section>
  <section class="pk-section pk-pale pk-mobile-packages"><div class="pk-wrap"><h2>Пакеты испытаний</h2><div class="pk-grid"><article class="pk-card"><h3>Локальный</h3><p><b>Точки:</b> одна зона или ограниченная группа.</p><p><b>Результат:</b> акт по проверенным точкам.</p><p><b>Повторное испытание:</b> не входит.</p></article><article class="pk-card"><h3>Объект</h3><p><b>Точки:</b> согласованный перечень на объекте.</p><p><b>Результат:</b> сводный акт и замечания.</p><p><b>Повторное испытание:</b> отдельно согласуется.</p></article><article class="pk-card"><h3>Объект плюс</h3><p><b>Точки:</b> согласованный объект.</p><p><b>Результат:</b> акт, дефектовка и план устранения.</p><p><b>Повторное испытание:</b> после устранения замечаний.</p></article></div></div></section>
  <section class="pk-section" id="pk-calculator"><div class="pk-wrap"><form class="pk-form"><h2>Предварительный расчёт испытаний</h2><p class="pk-note">Результат покажет состав расчёта. Точную стоимость подтвердим после проверки перечня точек и состояния системы.</p><div class="pk-fields"><label>Тип объекта<select required><option value="">Выберите</option><option>Офис / бизнес-центр</option><option>Ресторан / магазин</option><option>Складское помещение</option><option>Производство / завод</option><option>Государственный объект</option><option>Другое</option></select></label><label>Количество кранов<select required><option value="">Выберите</option><option>До 10</option><option>11–30</option><option>Более 30</option></select></label><label>Этажи / зоны<select required><option value="">Выберите</option><option>Одна зона</option><option>2–5 зон</option><option>Более 5 зон</option></select></label><label>Доступ к шкафам<select required><option value="">Выберите</option><option>Свободный</option><option>Частичный</option><option>Нужен пропуск или согласование</option></select></label><label>Акт и повторное испытание<select required><option value="">Выберите</option><option>Нужен акт</option><option>Нужно устранение замечаний</option><option>Нужно повторное испытание</option></select></label><label>Пакет<select required><option value="">Выберите</option><option>Локальный</option><option>Объект</option><option>Объект плюс</option></select></label></div><p><button class="pk-btn">Показать состав расчёта</button></p><div class="pk-result" hidden></div></form></div></section>
  <section class="pk-section pk-pale"><div class="pk-wrap"><h2>Фото работ, пример акта и кейсы</h2><p class="pk-note">Загрузим согласованные материалы без адресов и персональных данных.</p><div class="pk-grid"><div class="pk-placeholder">Пожарный шкаф до проверки</div><div class="pk-placeholder">Рукав и ствол</div><div class="pk-placeholder">Подключение измерительного оборудования</div><div class="pk-placeholder">Показания прибора</div><div class="pk-placeholder">Выявленное замечание</div><div class="pk-placeholder">Итоговая комплектация</div></div><div class="pk-grid" style="margin-top:16px"><div class="pk-placeholder">Кейс: тип объекта → количество точек → выявлено → передано заказчику</div><div class="pk-placeholder">Кейс: добавим после подтверждения</div><div class="pk-placeholder">Обезличенный пример акта испытаний — добавим после согласования</div></div></div></section>
  <section class="pk-section"><div class="pk-wrap"><h2>Вопросы до обращения</h2><details><summary>Что именно проверяется?</summary><p>Пожарные краны, согласованные точки и измеряемые параметры по утверждённой методике.</p></details><details><summary>От чего зависит цена?</summary><p>От количества кранов, этажей и зон, доступа, состояния системы, акта и дополнительных работ.</p></details><details><summary>Как подготовить объект?</summary><p>Обеспечить доступ к шкафам и назначить ответственного представителя.</p></details><details><summary>Сколько времени занимает работа?</summary><p>Срок уточняется после подтверждения состава точек и условий объекта.</p></details><details><summary>Какой документ получает заказчик?</summary><p>Акт испытаний по согласованному перечню и, при наличии, перечень замечаний.</p></details><details><summary>Входят ли ремонт и повторное испытание?</summary><p>Только по выбранному пакету или отдельному согласованию.</p></details><p class="pk-note">Ответы подтверждаются пожарным инженером перед публикацией.</p></div></section>
  <section class="pk-section pk-pale" id="pk-order"><div class="pk-wrap"><div class="pk-grid"><form class="pk-form"><h2>Заказать испытания</h2><div class="pk-fields"><label>Пакет<select required><option value="">Выберите</option><option>Локальный</option><option>Объект</option><option>Объект плюс</option></select></label><label>Город / область<select required><option value="">Выберите</option><option>Алматы</option><option>Алматинская область</option></select></label><label>Адрес объекта<input required></label><label>Количество кранов<input required></label><label>Имя<input required></label><label>Телефон<input required type="tel" placeholder="+7 (7XX) XXX-XX-XX"></label></div><p><button class="pk-btn">Заказать испытания</button></p><div class="pk-result" hidden></div></form><form class="pk-form"><h2>Получить консультацию</h2><p class="pk-note">Оставьте имя и телефон — уточним вопрос при звонке.</p><div class="pk-fields"><label>Имя<input required></label><label>Телефон<input required type="tel" placeholder="+7 (7XX) XXX-XX-XX"></label></div><p><button class="pk-btn">Получить консультацию</button></p><div class="pk-result" hidden></div></form></div></div></section>`;
  const titleSections = [...root.querySelectorAll('section')];
  const packageSection = titleSections.find(section => section.querySelector('h2')?.textContent === 'Пакеты испытаний');
  if (packageSection) {
    packageSection.querySelector('h2').textContent = 'Пакеты испытаний по ТЗ';
    const cards = packageSection.querySelectorAll('.pk-card');
    if (cards[0]) cards[0].innerHTML = '<h3>Локальный</h3><p>Одна зона или ограниченная группа кранов.</p><p>Измерения и акт по проверенным точкам.</p><p><b>от 25 000 ₸</b></p><p class="pk-note">Окончательную стоимость подтвердим после проверки исходных данных.</p><a class="pk-btn" href="#pk-order">Выбрать пакет</a>';
    if (cards[1]) cards[1].innerHTML = '<h3>Объект</h3><p>Согласованный перечень пожарных кранов на объекте.</p><p>Сводный акт и перечень замечаний.</p><p><b>от 100 000 ₸</b></p><p class="pk-note">Окончательную стоимость подтвердим после проверки исходных данных.</p><a class="pk-btn" href="#pk-order">Выбрать пакет</a>';
    if (cards[2]) cards[2].innerHTML = '<h3>Объект плюс</h3><p>Испытания, дефектовка, согласованное устранение доступных замечаний и повторная проверка.</p><p><b>от 120 000 ₸</b></p><p class="pk-note">Окончательную стоимость подтвердим после проверки исходных данных.</p><a class="pk-btn" href="#pk-order">Выбрать пакет</a>';
  }
  titleSections.find(section => section.querySelector('h2')?.textContent === 'Сравнение пакетов')?.remove();
  root.querySelector('.pk-mobile-packages')?.remove();
  titleSections.find(section => section.querySelector('h2')?.textContent === 'Фото работ, пример акта и кейсы')?.remove();
  root.querySelector('.pk-hero-choice h2, .pk-hero .pk-form h2')?.replaceChildren('Предварительный расчёт по параметрам объекта');
  const heroText = root.querySelector('.pk-hero .pk-form .pk-note');
  if (heroText) heroText.textContent = 'Для расчёта нужны: количество кранов, этажи и зоны, доступ к шкафам, наличие рукавов и стволов, известные неисправности, акт, устранение замечаний и повторное испытание.';
  [...root.querySelectorAll('.pk-hero .pk-wrap > div:first-child > p')]
    .find(paragraph => paragraph.textContent.includes('Методику и применимость'))
    ?.replaceChildren('Состав работ и методику испытаний подтвердим после уточнения параметров объекта.');
  [...root.querySelectorAll('.pk-hero a')].find(link => link.textContent.trim() === 'Рассчитать состав работ')?.remove();
  const heroCta = root.querySelector('.pk-hero a.pk-btn');
  if (heroCta) {
    heroCta.href = '#pk-calculator';
    heroCta.textContent = 'Рассчитать стоимость испытаний';
  }
  root.querySelectorAll('.pk-section').forEach(section => {
    if (section.querySelector('h2')?.textContent === 'Когда нужны испытания') {
      section.querySelectorAll('.pk-card')[2]?.remove();
      const flow = section.querySelectorAll('.pk-card')[0];
      if (flow) flow.innerHTML = '<h3>Слабая водоотдача или нестабильное давление</h3><p><b>Наблюдение:</b> требуется проверить параметры на согласованных точках.</p><p><b>Способ проверки:</b> испытание и измерение параметров.</p><p><b>Результат:</b> фиксация измерений по каждой точке в акте.</p>';
      const problem = section.querySelectorAll('.pk-card')[1];
      if (problem) problem.innerHTML = '<h3>Неисправный вентиль, рукав, ствол или неполная комплектация пожарного шкафа</h3><p><b>Наблюдение:</b> комплектность или исправность элементов вызывает сомнение.</p><p><b>Способ проверки:</b> осмотр шкафа, вентиля, рукава и ствола на согласованных точках.</p><p><b>Результат:</b> фиксация выявленных замечаний в акте.</p>';
    }
    if (section.querySelector('h2')?.textContent === 'Шесть этапов испытаний') section.querySelector('.pk-note')?.remove();
  });
  const calculator = root.querySelector('#pk-calculator');
  if (calculator) {
    calculator.querySelector('h2').textContent = 'Параметры расчёта из ТЗ';
    calculator.querySelector('.pk-note').textContent = 'Тип объекта, район, количество кранов, этажи и зоны, доступ, комплектация, неисправности, акт, устранение замечаний и повторное испытание — параметры, указанные в ТЗ.';
    calculator.querySelector('label:last-of-type')?.remove();
    calculator.querySelector('.pk-fields').insertAdjacentHTML('afterbegin', '<label>Район / область<select required><option value="">Выберите</option><option>Алматы</option><option>Алматинская область</option></select></label>');
    calculator.querySelector('.pk-fields').insertAdjacentHTML('beforeend', '<label>Наличие рукавов и стволов<select required><option value="">Выберите</option><option>Комплектация есть</option><option>Комплектация неполная</option><option>Неизвестно</option></select></label><label>Известные неисправности<select required><option value="">Выберите</option><option>Нет данных</option><option>Слабая водоотдача или давление</option><option>Неисправны вентиль, рукав или ствол</option><option>Другое</option></select></label>');
  }
  const order = root.querySelector('#pk-order');
  if (order) {
    order.querySelector('.pk-grid > form:last-child')?.remove();
    const orderForm = order.querySelector('form');
    orderForm?.querySelector('label:first-child')?.remove();
  }
  const style = document.createElement('style');
  style.textContent = '@media(min-width:821px){#pz-ispytaniya-pk-page .pk-mobile-packages{display:none}}@media(max-width:820px){#pz-ispytaniya-pk-page .pk-mobile-packages{display:block}#pz-ispytaniya-pk-page .pk-mobile-packages .pk-grid{grid-template-columns:1fr}#pz-ispytaniya-pk-page .pk-mobile-packages~*{}#pz-ispytaniya-pk-page .pk-section:has(table){display:none}}';
  root.prepend(style);
  root.querySelectorAll('select').forEach(select => { if (!select.closest('label')?.textContent.trim().startsWith('Тип объекта')) return; const label=document.createElement('label'); label.textContent='Укажите тип объекта'; const input=document.createElement('input'); input.required=false; label.style.display='none'; label.append(input); select.closest('label').insertAdjacentElement('afterend',label); select.addEventListener('change',()=>{const other=select.value==='Другое';label.style.display=other?'flex':'none';input.required=other;if(!other)input.value='';}); });
  root.querySelectorAll('form').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); if (!form.reportValidity()) return; const result=form.querySelector('.pk-result'); result.hidden=false; result.innerHTML=form.closest('#pk-calculator') ? '<b>Состав расчёта сформирован.</b><br>Подтвердим точную стоимость после проверки перечня кранов, этажей/зон, доступа и состояния системы.' : '<b>Данные приняты.</b><br>Свяжемся с вами в рабочее время.'; }));
  const calculatorForm = root.querySelector('#pk-calculator form');
  calculatorForm?.addEventListener('submit', () => {
    if (!calculatorForm.reportValidity()) return;
    const count = [...calculatorForm.querySelectorAll('label')].find(label => label.textContent.trim().startsWith('Количество кранов'))?.querySelector('select')?.value;
    const prices = {'До 10':'от 25 000 ₸','11–30':'от 50 000 ₸','Более 30':'от 100 000 ₸'};
    const result = calculatorForm.querySelector('.pk-result');
    result.hidden = false;
    result.innerHTML = `<b>Предварительная стоимость: ${prices[count] || 'уточняется'}.</b><br>В расчёт войдут испытания по указанным параметрам. Окончательная стоимость зависит от количества кранов, этажности, доступа, состояния системы и необходимости устранения замечаний.`;
  });
})();
