(function(){
  'use strict';
  var root=document.getElementById('pz-home-page');
  if(!root||root.dataset.homeInitialized)return;
  root.dataset.homeInitialized='true';
  var config=Object.assign({leadEndpoint:'',policyUrl:'',policyApproved:false,responseTimeText:'Мы свяжемся с вами в рабочее время и согласуем следующий шаг.',priceRules:{}},window.PozharnikHomeConfig||{});
  var serviceRoutes={aps_maintenance:'/obsluzhivanie/',aps_installation:'/montazh/',fire_audit:'/audit/',aps_repair:'/srabotka/',emergency_visit:'/srabotka/',aps_modernization:'/srabotka/',inspection:'/smena-podryadchika/'};
  root.addEventListener('click',function(e){var link=e.target.closest('[data-service]');if(!link||!serviceRoutes[link.dataset.service])return;if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();window.location.href=serviceRoutes[link.dataset.service]});
  window.setTimeout(function(){var photoBlock=$('#pz-real-photo');if(!photoBlock||photoBlock.dataset.workPhotos)return;photoBlock.dataset.workPhotos='true';var grid=document.createElement('div');grid.className='pz-grid';grid.style.marginTop='20px';grid.innerHTML='<figure class="pz-case"><div class="pz-case-image"><img src="media/resanta-diagnostika-ipr.png" alt="Проверка оборудования пожарной сигнализации" loading="lazy"></div><figcaption class="pz-case-body"><div class="pz-case-label">Диагностика АПС</div><h3>Проверка оборудования</h3><p>Осмотр и диагностика элементов системы пожарной сигнализации.</p></figcaption></figure><figure class="pz-case"><div class="pz-case-image"><img src="media/resanta-test-ipr.png" alt="Проверка ручного пожарного извещателя" loading="lazy"></div><figcaption class="pz-case-body"><div class="pz-case-label">Тестирование АПС</div><h3>Проверка ручного извещателя</h3><p>Тестирование извещателя и контроль работы системы.</p></figcaption></figure>';photoBlock.querySelector('.pz-wrap').appendChild(grid)},0);
  window.setTimeout(function(){var p=$('#pz-real-photo');if(!p)return;var g=document.createElement('div');g.className='pz-grid';g.innerHTML='<figure class="pz-case"><img src="media/frames/video5255746815780758564-08.jpg" alt="Тестирование ручного пожарного извещателя" loading="lazy"><figcaption class="pz-case-body"><h3>Тестирование ИПР</h3><p>Проверка работы ручного пожарного извещателя после восстановления.</p></figcaption></figure><figure class="pz-case"><img src="media/frames/video5255746815780758566-03.jpg" alt="Панель пожарной сигнализации" loading="lazy"><figcaption class="pz-case-body"><h3>Проверка панели АПС</h3><p>Диагностика состояния системы и индикации прибора.</p></figcaption></figure><figure class="pz-case"><img src="media/frames/video5255746815780758612-08.jpg" alt="Работа с оборудованием пожарной сигнализации" loading="lazy"><figcaption class="pz-case-body"><h3>Программирование прибора</h3><p>Работа с оборудованием после выявления неисправности.</p></figcaption></figure>';p.querySelector('.pz-wrap').appendChild(g)},50);
  window.setTimeout(function(){var figures=root.querySelectorAll('#pz-real-photo figure');figures.forEach(function(figure){var image=figure.querySelector('img[src*="/frames/"]');if(!image)return;var title=figure.querySelector('h3');if(title)title.textContent=image.src.indexOf('8564')>-1?'Проверка ручного извещателя':image.src.indexOf('8566')>-1?'Проверка панели АПС':'Работа с оборудованием АПС';var text=figure.querySelector('p');if(text)text.textContent='Кадр с работ по диагностике и проверке системы пожарной сигнализации.'})},100);
  var form=root.querySelector('#pz-lead-form');
  var primaryCta=root.querySelector('.pz-hero .pz-actions a');
  if(primaryCta){primaryCta.href='#pz-calculator';primaryCta.removeAttribute('data-service');primaryCta.dataset.analyticsLabel='Получить расчет';}
  if(form){
    ['organization','object_type','object_area','object_region'].forEach(function(name){var input=form.querySelector('[name="'+name+'"]');if(!input)return;input.required=false;var label=input.closest('label');if(label&&!label.dataset.optional){var title=label.firstChild;if(title&&title.nodeType===3)title.textContent=title.textContent.trim()+' (необязательно)';label.dataset.optional='true'}});
  }
  var proof=root.querySelector('.pz-proof');
  if(proof&&!root.querySelector('#pz-early-evidence')){
    proof.insertAdjacentHTML('afterend','<section id="pz-early-evidence" class="pz-early-evidence" aria-labelledby="pz-early-evidence-title"><div class="pz-wrap"><div class="pz-head"><div><div class="pz-eyebrow">Примеры работ</div><h2 id="pz-early-evidence-title">Что уже делали на действующей АПС</h2></div><p>Объекты не называем. Показываем работы и результат по предоставленным материалам.</p></div><div class="pz-early-evidence-grid"><article><img src="/media/diagnostika-bloka-pitaniya-aps.png" alt="Диагностика блока питания АПС" loading="lazy"><div><b>Проверка питания АПС</b><p>Измерили параметры блока питания, чтобы определить дальнейшие действия по системе.</p></div></article><article><img src="/media/resanta-diagnostika-ipr.png" alt="Диагностика ручного пожарного извещателя" loading="lazy"><div><b>Восстановление ИПР</b><p>Провели диагностику и программирование прибора для корректной работы.</p></div></article><article><img src="/media/resanta-test-ipr.png" alt="Тестирование ручного пожарного извещателя" loading="lazy"><div><b>Тестирование извещателя</b><p>Проверили работу системы после выявления неисправности.</p></div></article></div><div class="pz-early-evidence-action"><a class="pz-btn" href="#pz-calculator">Выбрать услугу и получить разбор ↗</a><span>Обработаем заявку в течение 10 минут в рабочее время.</span></div></div></section><style>#pz-home-page .pz-early-evidence{padding:55px 0;background:#f5f7f6}#pz-home-page .pz-early-evidence-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:28px}#pz-home-page .pz-early-evidence article{background:#fff;border:1px solid #dfe6e8;border-radius:12px;overflow:hidden}#pz-home-page .pz-early-evidence img{width:100%;aspect-ratio:16/10;object-fit:cover;display:block}#pz-home-page .pz-early-evidence article div{padding:18px}#pz-home-page .pz-early-evidence p{font-size:14px;color:#697984;margin:8px 0 0}#pz-home-page .pz-early-evidence-action{display:flex;align-items:center;gap:20px;flex-wrap:wrap;margin-top:26px}#pz-home-page .pz-early-evidence-action span{font-size:14px;font-weight:700;color:#14364b}@media(max-width:820px){#pz-home-page .pz-early-evidence-grid{grid-template-columns:1fr}}<\/style>');
  }
  var evidence=root.querySelector('#pz-early-evidence');
  if(evidence){
    var evidenceTitle=evidence.querySelector('h2');
    if(evidenceTitle)evidenceTitle.textContent='Диагностика, восстановление и тестирование АПС';
    var evidenceLead=evidence.querySelector('.pz-head p');
    if(evidenceLead)evidenceLead.textContent='Фотографии с выполненных работ. Наименования объектов не раскрываются.';
    var evidenceCards=evidence.querySelectorAll('.pz-early-evidence article');
    var evidenceCopy=[
      ['Диагностика блока питания','Проверка параметров питания системы с помощью мультиметра.'],
      ['Восстановление ИПР и программирование прибора','Восстановили ручной извещатель и выполнили программирование для исправной работы.'],
      ['Тестирование системы и перепрограммирование','При тестировании выявили неисправность, выполнили перепрограммирование и завершили проверку работы системы.']
    ];
    evidenceCards.forEach(function(card,index){var text=evidenceCopy[index];if(!text)return;var title=card.querySelector('b'),description=card.querySelector('p');if(title)title.textContent=text[0];if(description)description.textContent=text[1]});
  }
  ['#pz-real-photo','#pz-gallery'].forEach(function(selector){var block=root.querySelector(selector);if(block)block.hidden=true});
  var $=function(s,el){return (el||root).querySelector(s)};
  var calculatorHub=$('#pz-calculator');if(calculatorHub&&!$('#pz-calculator-pages')){calculatorHub.insertAdjacentHTML('beforeend','<div id="pz-calculator-pages" class="pz-calculator-pages"><p>Выберите специализированный калькулятор:</p><div><a href="/kalkulyatory/obsluzhivanie/">Обслуживание АПС ↗</a><a href="/kalkulyatory/montazh/">Монтаж АПС ↗</a><a href="/kalkulyatory/audit/">Пожарный аудит ↗</a></div></div>');root.insertAdjacentHTML('beforeend','<style>.pz-calculator-pages{margin-top:24px;padding:20px;border:1px solid #dfe6e8;border-radius:13px;background:#fff}.pz-calculator-pages p{margin:0 0 10px;font-weight:700}.pz-calculator-pages div{display:flex;flex-wrap:wrap;gap:12px}.pz-calculator-pages a{color:#14364b;font-weight:700;text-decoration:underline}</style>')}
  var gallery=$('#pz-gallery');if(gallery&&!$('#pz-real-photo')){var realPhoto=document.createElement('section');realPhoto.id='pz-real-photo';realPhoto.className='pz-section';realPhoto.innerHTML='<div class="pz-wrap"><div class="pz-head"><div><div class="pz-eyebrow">Фото с работ</div><h2>Диагностика питания АПС</h2></div><p>Реальный кадр диагностики блока питания. Данные объекта не раскрываются.</p></div><figure class="pz-case" style="max-width:620px"><div class="pz-case-image"><img src="media/diagnostika-bloka-pitaniya-aps.png" alt="Инженер выполняет диагностику блока питания АПС мультиметром" width="1280" height="960" loading="lazy"><span class="pz-play" aria-hidden="true">⌁</span></div><figcaption class="pz-case-body"><div class="pz-case-label">Диагностика</div><h3>Проверка питания системы</h3><p>Объект, площадь, срок и результат укажем только после согласования.</p></figcaption></figure></div>';gallery.parentNode.insertBefore(realPhoto,gallery)}
  function push(event,params){window.dataLayer=window.dataLayer||[];window.dataLayer.push(Object.assign({event:event},params||{}))}
  function uid(){return window.crypto&&window.crypto.randomUUID?window.crypto.randomUUID():'pz-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
  function hidden(f,name,value){var el=f.querySelector('input[name="'+name+'"]');if(!el){el=document.createElement('input');el.type='hidden';el.name=name;f.appendChild(el)}el.value=value==null?'':String(value);return el}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function field(f,n){return f.elements.namedItem(n)}
  function icp(service){return {aps_maintenance:'ICP-1',inspection:'ICP-2',aps_installation:'ICP-3',aps_design:'ICP-3',aps_repair:'ICP-4',aps_modernization:'ICP-4',emergency_visit:'ICP-4',fire_audit:'ICP-5'}[service]||'ICP-C'}
  function actionFields(f){var isVisit=field(f,'requested_action').value==='visit';f.querySelectorAll('[data-visit]').forEach(function(label){label.hidden=!isVisit;var input=label.querySelector('input,select');input.disabled=!isVisit;input.required=isVisit&&input.name==='object_address'});var b=f.querySelector('button[type="submit"]');if(b)b.innerHTML=(isVisit?'Назначить выезд':'Получить расчет')+' <span aria-hidden="true">↗</span>';hidden(f,'icp_type',icp(field(f,'service').value))}
  function setGoal(service,action){if(field(form,'service').querySelector('option[value="'+service+'"]'))field(form,'service').value=service;var choice=form.querySelector('[name="requested_action"][value="'+action+'"]');if(choice)choice.checked=true;actionFields(form)}
  root.querySelectorAll('a[href="#pz-request"][data-service]').forEach(function(a){a.addEventListener('click',function(){setGoal(a.dataset.service,a.dataset.action||'calculation');hidden(form,'lead_type',a.dataset.analyticsLocation==='hero'?'homepage_express':'homepage_final');hidden(form,'form_name','lead_home_shared');form.dataset.analyticsForm='lead_home_shared';hidden(form,'lead_source_block',a.dataset.analyticsLocation||'services');hidden(form,'cta_location',a.dataset.analyticsLocation||'services');hidden(form,'cta_text',a.dataset.analyticsLabel||a.textContent.trim());var pack=a.dataset.package||'';hidden(form,'selected_package',pack);if(pack)push('pz_package_select',{selected_package:pack});if(a.dataset.object){var map={'Склады и логистика':'Склад / логистика','Производство':'Производство','Офисы и бизнес-центры':'Бизнес-центр / офис','Торговля':'Торговля','HoReCa':'HoReCa','Медицинские объекты':'Медицинский объект'};field(form,'object_type').value=map[a.dataset.object]||'Другое'}})});
  form.addEventListener('change',function(e){if(e.target.name==='requested_action'||e.target.name==='service')actionFields(form)});actionFields(form);
  root.addEventListener('click',function(e){var a=e.target.closest('a[href="#pz-request"][data-service]');if(a){form.dataset.originLocation=a.dataset.analyticsLocation||'services';form.dataset.originLabel=a.dataset.analyticsLabel||a.textContent.trim()}});
  function phoneMask(input){input.addEventListener('input',function(){var digits=input.value.replace(/\D/g,'');if(digits[0]==='8')digits='7'+digits.slice(1);if(digits&&digits[0]!=='7')digits='7'+digits;digits=digits.slice(0,11);var n=digits.slice(1);input.value=digits?'+7'+(n?' ('+n.slice(0,3):'')+(n.length>=3?') ':'')+(n.length>3?n.slice(3,6):'')+(n.length>6?'-'+n.slice(6,8):'')+(n.length>8?'-'+n.slice(8,10):''):'';input.setCustomValidity(digits.length===11&&digits[1]==='7'?'':digits?'Введите полный номер Казахстана +7 (7XX) XXX-XX-XX':'')})}
  function initPhone(f){f.querySelectorAll('input[type="tel"]').forEach(phoneMask)}initPhone(form);
  function policyClick(e){e.preventDefault();if(config.policyUrl&&/^https:\/\//.test(config.policyUrl)){window.open(config.policyUrl,'_blank','noopener');return}showDialog($('#pz-privacy'))}
  root.querySelectorAll('[data-policy]').forEach(function(a){a.addEventListener('click',policyClick)});
  var lastFocus;
  function showDialog(d){lastFocus=document.activeElement;if(typeof d.showModal==='function'){d.showModal();d.querySelector('button').focus()}else{d.setAttribute('open','');d.querySelector('button').focus()}}
  root.querySelectorAll('dialog').forEach(function(d){d.querySelector('[data-close]').addEventListener('click',function(){d.close()});d.addEventListener('click',function(e){var b=d.getBoundingClientRect();if(e.target===d&&(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom))d.close()});d.addEventListener('close',function(){if(lastFocus)lastFocus.focus()})});
  root.addEventListener('click',function(e){var image=e.target.closest('#pz-real-photo img');if(!image)return;var dialog=$('#pz-image-dialog'),title=image.closest('figure')&&image.closest('figure').querySelector('h3');if(!dialog)return;$('#pz-large-image').src=image.currentSrc||image.src;$('#pz-large-image').alt=image.alt||'Фото с работ';$('#pz-image-title').textContent=title?title.textContent:'Фото с работ';var original=$('#pz-video-original');original.hidden=true;original.removeAttribute('href');showDialog(dialog)});
  root.querySelectorAll('[data-gallery]').forEach(function(b){b.addEventListener('click',function(){var im=$('#pz-large-image');im.src='https://i.ytimg.com/vi/'+b.dataset.gallery+'/hqdefault.jpg';im.alt=b.dataset.caption;$('#pz-image-title').textContent=b.dataset.caption;$('#pz-video-original').href='https://www.youtube.com/watch?v='+b.dataset.gallery;showDialog($('#pz-image-dialog'))})});
  // Additional business UI events do not duplicate the global pz_cta_click.
  root.addEventListener('click',function(e){var a=e.target.closest('a');if(!a)return;var href=a.getAttribute('href')||'';if(href.indexOf('tel:')===0||href.indexOf('https://wa.me/')===0)push('pz_contact_click',{cta_type:href.indexOf('tel:')===0?'phone':'whatsapp',cta_location:a.dataset.analyticsLocation||'global'})});
  async function submitLead(f){
    var err=f.querySelector('.pz-error'),ok=f.querySelector('.pz-success');err.hidden=true;ok.hidden=true;
    if(!f.reportValidity())return;
    if(!config.leadEndpoint||!config.policyApproved){err.textContent='Онлайн-отправка пока недоступна. Позвоните +7 771 193 4976 или обсудите объект в WhatsApp — контакты есть на странице.';err.hidden=false;return}
    if(!/^https:\/\//.test(config.leadEndpoint)){err.textContent='Не удалось отправить обращение. Пожалуйста, свяжитесь с нами по телефону.';err.hidden=false;return}
    var button=f.querySelector('button[type="submit"]');if(button.disabled)return;
    if(window.PozharnikAnalytics)window.PozharnikAnalytics.enrichAllForms();
    var id=field(f,'event_id');if(!id||!id.value)id=hidden(f,'event_id',uid());
    var eventId=id.value;hidden(f,'icp_type',icp(field(f,'service').value));
    var service=field(f,'service').value,goal=field(f,'requested_action').value;
    // Keep this page's selected source rather than the global last submit button.
    var origin=f.dataset.originLocation||(f.id==='pz-calculator-form'?'calculator':'footer');
    hidden(f,'lead_source_block',origin);hidden(f,'cta_location',origin);hidden(f,'cta_text',f.dataset.originLabel||(f.id==='pz-calculator-form'?'Результат калькулятора':'Общая форма'));
    var last;try{last=JSON.parse((field(f,'utm_last_json')||{}).value||'null')}catch(ignore){}
    if(last)['gclid','gbraid','wbraid','yclid'].forEach(function(k){hidden(f,k,last[k]||'')});
    button.disabled=true;var old=button.innerHTML;button.textContent='Отправляем…';
    var controller=new AbortController(),timeout=window.setTimeout(function(){controller.abort()},20000);
    try{
      if(window.gtag){var cid=await new Promise(function(resolve){var done=false;var timer=window.setTimeout(function(){if(!done){done=true;resolve('')}},1200);if(!config.gaMeasurementId){window.clearTimeout(timer);resolve('');return}try{window.gtag('get',config.gaMeasurementId,'client_id',function(value){if(!done){done=true;window.clearTimeout(timer);resolve(value||'')}})}catch(ignore){window.clearTimeout(timer);resolve('')}});if(cid)hidden(f,'ga_client_id',cid)}
      var res=await fetch(config.leadEndpoint,{method:'POST',body:new URLSearchParams(new FormData(f)),signal:controller.signal,credentials:'omit'});
      var data=await res.json();
      if(!res.ok||data.accepted!==true||!data.lead_id)throw new Error('not_accepted');
      // The CRM adapter must confirm durable lead acceptance, not just an analytics write.
      if(window.PozharnikAnalytics){f.dispatchEvent(new CustomEvent('tildaform:aftersuccess',{bubbles:true,detail:{source:'pozharnik_server_adapter',lead_id:data.lead_id}}))}
      else push('pz_form_success',{event_id:eventId,form_name:f.dataset.analyticsForm,service:service,requested_action:goal});
      f.reset();hidden(f,'event_id','');if(f===form)actionFields(f);
      ok.textContent=data.response_time_text||config.responseTimeText;ok.hidden=false;
    }catch(e){err.textContent=e.name==='AbortError'?'Ответ задерживается. Заявка могла быть принята: повторите с тем же идентификатором или свяжитесь по телефону.':'Не удалось подтвердить отправку. Повторите попытку или позвоните +7 771 193 4976.';err.hidden=false;push('pz_form_error',{event_id:eventId,form_name:f.dataset.analyticsForm,error_type:e.name==='AbortError'?'timeout':'network_or_not_accepted'})}
    finally{window.clearTimeout(timeout);button.disabled=false;button.innerHTML=old;if(f===form)actionFields(f)}
  }
  function bindForm(f){f.addEventListener('submit',function(e){e.preventDefault();submitLead(f)})}bindForm(form);
  var mobileBar=$('.pz-mobile-bar'),obscuring=new Set();
  var barObserver=window.IntersectionObserver?new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting)obscuring.add(e.target);else obscuring.delete(e.target)});mobileBar.hidden=obscuring.size>0},{threshold:0}):null;
  if(barObserver){barObserver.observe(form);barObserver.observe($('.pz-footer'))}
  var step=0,started=false,answers={service:'',object_type:'',object_area:'',object_count:1},resultText='';
  var quiz=$('#pz-quiz-content'),next=$('#pz-quiz-next'),back=$('#pz-quiz-back'),message=$('#pz-quiz-message');
  var tasks=[['aps_maintenance','Обслуживание АПС'],['inspection','Смена подрядчика'],['aps_installation','Монтаж новой системы'],['aps_repair','Ремонт / модернизация'],['fire_audit','Аудит / проверка']];
  var types=['Склад / логистика','Производство','Бизнес-центр / офис','Торговля','HoReCa','Медицинский объект','Другое'];
  function selectHtml(name,list,selected){return '<select name="'+name+'" required><option value="">Выберите вариант</option>'+list.map(function(v){var val=Array.isArray(v)?v[0]:v,label=Array.isArray(v)?v[1]:v;return '<option value="'+esc(val)+'" '+(selected===val?'selected':'')+'>'+esc(label)+'</option>'}).join('')+'</select>'}
  function labelInput(label,name,type,value,extra){return '<label class="pz-field">'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+(extra||'')+'></label>'}
  function taskTitle(){return (tasks.find(function(t){return t[0]===answers.service})||['',''])[1]}
  function calculate(){var rule=config.priceRules[answers.service];var rate=rule&&rule.byObject&&rule.byObject[answers.object_type]||rule;if(rate&&rate.minPerM2>0&&rate.maxPerM2>=rate.minPerM2){var min=Math.max(rate.minimum||0,Math.round(Number(answers.object_area)*rate.minPerM2)),max=Math.max(min,Math.round(Number(answers.object_area)*rate.maxPerM2));return {title:min.toLocaleString('ru-RU')+'–'+max.toLocaleString('ru-RU')+' ₸'+(answers.service==='aps_maintenance'?' / месяц':''),text:'Предварительная вилка по согласованной тарифной модели. Точный состав, оборудование и условия уточняются по объекту.'}}
    if(answers.service==='aps_installation'&&answers.project_exists==='Да')return {title:'Следующий шаг — расчет по проекту',text:'Для персональной сметы понадобятся планы и спецификация оборудования. Передайте контакт — согласуем исходные данные и срок расчета.'};
    return {title:'Сначала — обследование системы',text:answers.service==='fire_audit'?'Для аудита уточним состав объекта, документацию и дату проверки. После согласования объема подготовим стоимость и условия выезда.':'По одной площади точную стоимость не определить. Уточним оборудование и состояние системы, согласуем обследование и подготовим персональный расчет.'}}
  function render(){
    message.textContent='';$('#pz-step-label').textContent='Шаг '+(step+1)+' из 4';root.querySelectorAll('.pz-progress i').forEach(function(x,i){x.classList.toggle('active',i<=step)});back.hidden=step===0;next.hidden=step===3;
    if(step===0){quiz.innerHTML='<h3>Какая задача у вашего объекта?</h3><div class="pz-choice-grid">'+tasks.map(function(t){return '<button type="button" class="pz-choice" data-task="'+t[0]+'" aria-pressed="'+(answers.service===t[0])+'">'+t[1]+'</button>'}).join('')+'</div>';quiz.querySelectorAll('[data-task]').forEach(function(b){b.addEventListener('click',function(){answers.service=b.dataset.task;quiz.querySelectorAll('[data-task]').forEach(function(x){x.setAttribute('aria-pressed',x===b)});if(!started){started=true;push('pz_calculator_start',{calculator_type:'homepage_quick'})}})})}
    if(step===1){quiz.innerHTML='<h3>Расскажите об объекте</h3><div class="pz-fields"><label class="pz-field pz-full">Тип объекта'+selectHtml('object_type',types,answers.object_type)+'</label>'+labelInput('Площадь, м²','object_area','number',answers.object_area,'required min="1" max="100000000" step="1" inputmode="numeric" placeholder="Например, 3500"')+labelInput('Количество объектов','object_count','number',answers.object_count,'required min="1" max="10000" step="1" inputmode="numeric"')+'</div>'}
    if(step===2){var fields='';if(answers.service==='aps_maintenance'||answers.service==='inspection'){fields='<label class="pz-field">Действующая АПС'+selectHtml('aps_exists',['Да','Нет','Нужно уточнить'],answers.aps_exists)+'</label><label class="pz-field">Есть подрядчик?'+selectHtml('current_contractor',['Да','Нет'],answers.current_contractor)+'</label>'+labelInput('Окончание договора, если известно','contract_end_date','date',answers.contract_end_date,'')}
      else if(answers.service==='aps_installation'){fields='<label class="pz-field">Состояние объекта'+selectHtml('system_state',['С нуля','Реконструкция','Замена'],answers.system_state)+'</label><label class="pz-field">Есть проект?'+selectHtml('project_exists',['Да','Нет','В разработке'],answers.project_exists)+'</label>'}
      else if(answers.service==='aps_repair'){fields='<label class="pz-field">Что происходит?'+selectHtml('problem',['Ложные сработки','Ошибка на приборе','Отключенная зона','Устаревшая система','Другое'],answers.problem)+'</label><label class="pz-field">Срочность'+selectHtml('urgency',['Планово','Как можно скорее'],answers.urgency)+'</label>'}
      else fields=labelInput('Дата проверки, если известна','inspection_date','date',answers.inspection_date,'')+'<label class="pz-field">Есть замечания?'+selectHtml('known_issues',['Да','Нет','Нужно проверить'],answers.known_issues)+'</label>';
      quiz.innerHTML='<h3>Уточним задачу</h3><div class="pz-fields">'+fields+'</div>';next.innerHTML='Показать результат <span aria-hidden="true">→</span>'}
    if(step===3){var calculated=calculate();var r={title:'Предварительный разбор для объекта подготовлен',text:'Оставьте контакты — инженер сверит параметры, уточнит оборудование и пришлёт персональный следующий шаг. Данные калькулятора уже приложены к заявке.'};resultText=calculated.title;push('pz_calculator_complete',{calculator_type:'homepage_quick',result_range:calculated.title,service:answers.service});var goal=['inspection','aps_repair','fire_audit'].indexOf(answers.service)>-1?'visit':'calculation';
      quiz.innerHTML='<div class="pz-result"><h3>'+esc(r.title)+'</h3><p>'+esc(r.text)+'</p><small>'+esc(taskTitle())+' · '+esc(answers.object_type)+' · '+esc(answers.object_area)+' м² · '+esc(answers.object_count)+' объект(а)</small></div><form class="pz-form" id="pz-calculator-form" data-analytics-form="lead_home_calculator" novalidate style="border:0;padding:0"><input type="hidden" name="form_name" value="lead_home_calculator"><input type="hidden" name="form_id" value="pz-calculator-form"><input type="hidden" name="lead_type" value="calculation"><input type="hidden" name="requested_action" value="'+goal+'"><div class="pz-fields">'+labelInput('Имя','name','text','','required autocomplete="given-name" maxlength="100"')+labelInput('Организация','organization','text','','required autocomplete="organization" maxlength="150"')+labelInput('Телефон','phone','tel','','required autocomplete="tel" inputmode="tel" placeholder="+7 (7XX) XXX-XX-XX" pattern="\\+7 \\(7[0-9]{2}\\) [0-9]{3}-[0-9]{2}-[0-9]{2}"')+'<label class="pz-field">Регион объекта'+selectHtml('object_region',['Алматы','Алматинская область','Другой регион'],'')+'</label></div><label class="pz-consent"><input type="checkbox" name="consent" value="yes" required><span>Согласен на обработку данных обращения. <a href="#pz-privacy" data-policy>Условия обработки</a></span></label><button type="submit" class="pz-btn">'+(goal==='visit'?'Обсудить обследование':'Запросить персональный расчет')+' ↗</button><div class="pz-error" role="alert" hidden></div><div class="pz-success" role="status" hidden></div></form>';
      var f=$('#pz-calculator-form');Object.keys(answers).forEach(function(k){hidden(f,k,answers[k])});hidden(f,'calculator_answers',JSON.stringify(answers));hidden(f,'calculator_result',resultText);hidden(f,'lead_source_block','calculator');hidden(f,'cta_location','calculator');initPhone(f);bindForm(f);if(barObserver)barObserver.observe(f);f.querySelector('[data-policy]').addEventListener('click',policyClick);if(window.PozharnikAnalytics)window.PozharnikAnalytics.enrichAllForms()}
    if(step<2)next.innerHTML='Далее <span aria-hidden="true">→</span>';
  }
  next.addEventListener('click',function(){if(step===0&&!answers.service){message.textContent='Выберите задачу объекта.';return}if(step>0){var inputs=quiz.querySelectorAll('input,select');for(var i=0;i<inputs.length;i++){if(!inputs[i].reportValidity())return;answers[inputs[i].name]=inputs[i].value}}step=Math.min(3,step+1);render();var heading=quiz.querySelector('h3,h4');heading.tabIndex=-1;heading.focus({preventScroll:true})});
  back.addEventListener('click',function(){if(step>0&&step<3)quiz.querySelectorAll('input,select').forEach(function(i){answers[i.name]=i.value});step=Math.max(0,step-1);render()});render();
  window.PozharnikHome={setGoal:setGoal,config:config};
})();
